// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDM_aNU208cbwsMph4ZpjLen35IJCym-rY',
    appId: '1:115506620731:web:b0ad8eadecfcc3fafa2f1e',
    messagingSenderId: '115506620731',
    projectId: 'vize0302720128-75e8f',
    authDomain: 'vize0302720128-75e8f.firebaseapp.com',
    storageBucket: 'vize0302720128-75e8f.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBWjBsDuK7iV0pxbOyPQAm9AdsoGtVA2o4',
    appId: '1:115506620731:android:c2bcde7594cac7bafa2f1e',
    messagingSenderId: '115506620731',
    projectId: 'vize0302720128-75e8f',
    storageBucket: 'vize0302720128-75e8f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD6tLzEfx_eb_ueZ47iSF6X6yFfk1fgV7s',
    appId: '1:115506620731:ios:1531284616cd5ca3fa2f1e',
    messagingSenderId: '115506620731',
    projectId: 'vize0302720128-75e8f',
    storageBucket: 'vize0302720128-75e8f.appspot.com',
    iosClientId: '115506620731-hf8j6u8trc7387g1h1c15759ek0n3eih.apps.googleusercontent.com',
    iosBundleId: 'com.example.gtkFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD6tLzEfx_eb_ueZ47iSF6X6yFfk1fgV7s',
    appId: '1:115506620731:ios:1531284616cd5ca3fa2f1e',
    messagingSenderId: '115506620731',
    projectId: 'vize0302720128-75e8f',
    storageBucket: 'vize0302720128-75e8f.appspot.com',
    iosClientId: '115506620731-hf8j6u8trc7387g1h1c15759ek0n3eih.apps.googleusercontent.com',
    iosBundleId: 'com.example.gtkFlutter',
  );
}
